### ISSUE TITLE
"block future dates" causing "Future dates not allowed" error even when today's date is selected.

### ISSUE THREAD

**Issue by vasanthid** [PredixDev/px-rangepicker#14]
Steps to reproduce:

1. Used px-rangepicker 1.1.6 version

2. <px-rangepicker
        date-format="MM/DD/YY"
        time-format="hh:mm:ss A"
        show-buttons="true"
        block-future-dates="true"
        show-time-zone="none"
        preset-ranges="{{presetRanges}}"
        range="{{dateRange}}">
      </px-rangepicker>

     where dateRange = {
            "from": browser's local time - 8 hours,
            "to": browser's local time
          }
    

3.  It works fine during Pacific day time.  When around 5pm or after 5pm, 
      "Future dates not allowed" error is thrown and it blocks entire page from loading.

      Key here is to reproduce it after 5pm.  It works fine during day time.

It appears like time component is not aware of date component during validation.

This is very critical as it prevents entire app from loading.

**Comment by benoitjchevalier** [comment]
I have delivered a fix in px-datetime-common that removes the validation on the time base of the field, only making sure that the 'day' is before or after 'today'.

The fix is delivered in px-datetime-common v0.5.5 which should automatically be fetched if you reinstall px-rangepicker through bower. 

Please let me know if that solves your issue.

**Comment by benoitjchevalier** [comment]
Closing this issue now
