### ISSUE TITLE
On selecting “Presets” as “Last 7 Days”, “This Month”, “Last Month” the calendar widget also select/ highlights an additional day

### ISSUE THREAD

**Issue by surekhakolekar** [PredixDev/px-rangepicker#27]
Steps to Reproduce:-
1.Select “Last 7 Days”, “This Month”, “Last Month”
2.Observe the highlighted dates for each of the three selections

Actual- An extra day is getting selected

Expected- Proper dates should get selected

Please see the attached screenshot.
![extra date selected](https://cloud.githubusercontent.com/assets/1745071/22886198/d8fd63aa-f222-11e6-9cc5-3fa055edcd98.png)

**Comment by nonmetalhail** [comment]
That is actually working as expected. Yes, an "extra" date is in the range, but because it is from mid-day 31st to mid-day the 7th, that is 7 full days, ie 168 hours. If it went to the 1st, it would be 7 dates, but only a 6 days span.

If you want different preset behavior, you can customize it through the `presetRanges` array. As example, this is how it is currently configured:

```
    var now = Px.moment();

    [
        {
            "displayText": "Last 7 Days",
            "startDateTime": now.clone().subtract(7, 'days'),
            "endDateTime": now
        }, {
            "displayText": "This Month",
            "startDateTime": now.clone().startOf('month'),
            "endDateTime": now.clone().endOf('month')
       }, {
            "displayText": "Last Month",
            "startDateTime": now.clone().subtract(1, 'months').startOf('month'),
            "endDateTime": now.clone().subtract(1, 'months').endOf('month')
       }
    ]
```
