### ISSUE TITLE
Chosen Date Range not available to retrieve

### ISSUE THREAD

**Issue by snehadr23** [PredixDev/px-rangepicker#29]
Hi,

We are using the px-rangepicker component to get a date+time range. We have default values(current date+time) showing on load of the page, and when we choose different dates by opening the panel, the UI updates the view with the chosen values. The variable we pass in with the default range to the px-rangepicker doesn't get the updated values to be used in our controller. This component was working with our code until the morning of 2/13, but hasn't since though no code changes were pushed. Please let us know how we can resolve this.

Thanks

**Comment by Menkhaus-ge** [comment]
Hi @snehadr23, 

Can you please fill out the template below so that we have enough information to help you. 
A code example seems like it would be most helpful in this use case. 

Template: 
To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

## Steps to reproduce the problem:

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

## Screenshots (_optional, but very helpful_):

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
@snehadr23 Are you still having this issue or can this be closed? We still need more information or a codepen/repo that replicates the issue in order to help.
