### ISSUE TITLE
Support empty rangepicker

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-rangepicker#32]
see https://github.com/PredixDev/px-datetime-picker/issues/15

**Comment by benoitjchevalier** [comment]
coming soon

**Comment by benoitjchevalier** [comment]
done in v3.0.0

**Comment by shrau94** [comment]
It seems that this issue is solved but when i manually delete the selected date from the rangepicker from and to fields the date is still selected in the panel. (Refer screenshots)

![capture3](https://user-images.githubusercontent.com/10210384/35560146-929f52d2-05d2-11e8-93fd-82788192a765.JPG)

![capture4](https://user-images.githubusercontent.com/10210384/35560157-961b1004-05d2-11e8-8f2e-67690ca047c3.JPG)

**Comment by katemenkhaus** [comment]
Currently we don't have a way to clear the selection with the panel open. 
We are working on a fix for this.

**Comment by katemenkhaus** [comment]
#62

**Comment by shrau94** [comment]
Even when the panel is not open it still retains the earlier selected date when the fields are emptied. 
In the above case as well the panel was opened later to check if the from and to dates are updated. 
The px-rangepicker version that I am using is 3.0.2.
