### ISSUE TITLE
Cancel action does not clear the current selection for presets

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-rangepicker#33]
This should be a minor bug related to presets. When you select an option from the presets, then hit cancel, the presets still shows the current selection and does not go back to previously selected value.

This is reproducible in the demo page as well. 

https://www.predix-ui.com/#/components/px-rangepicker/

The date range works as expected. Only the presets are not showing up properly.

**Comment by madhuri-ch** [comment]
Select the preset Last Month and click on Apply. Now, the user has selected 'Last Month' and would expect to see if there are no further changes to it.

![Uploading New preselect - Cancel.png…]()

Now,  Select the preset 'This Month' and click on Cancel.. cancelling the selected preset 'This months' should highlight the previously selected preset "Last month" but instead it still shows 'This Month' being selected.

![Uploading Initial preset select-Apply.png…]()

**Comment by priyabrat1801** [comment]
Is there any ETA on the fix for this one?

**Comment by Menkhaus-ge** [comment]
I cannot recreate this issue on the latest version v2.0.1

**Comment by Manny0510** [comment]
I still see this issue following on demo page (https://www.predix-ui.com/#/components/px-rangepicker) the same steps. Apply one preset (First Preset) -> change the preset (Second Preset) and click cancel... you still see the Second preset(newly selected and discarded (Cancelled)) highlighted instead of the First.

**Comment by Menkhaus-ge** [comment]
I miss understood. I see that even though the selected dates are as expected, the highlighted preset is wrong.

**Comment by Menkhaus-ge** [comment]
We have push a fix for this in v1.0.3 of px-datetime-range-panel. 
The fix is if the user clicks cancel and the presets are open, the presets will all be reset. We did not try to save the state because that was a much larger effort and we believe this simple solution will alleviate the confusion the bug caused.
