### ISSUE TITLE
allow-wrap property

### ISSUE THREAD

**Issue by PJLindsay** [PredixDev/px-rangepicker#44]
Hi,

First of all - superb work so far! 
These are the *best* datetime picker controls I've seen so far.

## Expected behavior and actual behavior:

expected: allow-wrap property would be implemented similar to px-datetime-range-field
actual: property does not exist, time is "cut off" in narrow resolutions (e.g. mobile phone)

Ideally it would stack TO above FROM when you change to a narrower resolution

## Steps to reproduce the problem:
open in Chrome browser
open developer tools
click on 'toggle device bar' button (e.g. preview web page as it would look on a mobile phone)

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

macOS Sierra version 10.12.6
Chrome browser: Version 60.0.3112.90 (Official Build) (64-bit)
MBP

**Comment by randyaskin** [comment]
Thanks for the suggestion. Since rangepicker simply uses datetime-range-field, I've exposed the property through to the rangepicker API in v2.0.3. We know the datetime components overall need some responsiveness love - would be interested to hear if you have other ideas for making them more mobile friendly!
