### ISSUE TITLE
Add possibility to hide validation error

### ISSUE THREAD

**Issue by konraifen88** [PredixDev/px-rangepicker#46]
## Description
It would be great if we would be able to disable the validation message. The message is displayed without background and maybe over other elements. 

It seems that it is already implemented for `<px-datetime-field>` with the `showValidationMessage` property. This property is also available as protected one in the `<px-datetime-range-field>` implemented by the `<px-rangepicker>`. 

## Screenshots
![image](https://user-images.githubusercontent.com/9212363/30050373-885b9254-921e-11e7-9e14-c21eb8ba0da7.png)

**Comment by Menkhaus-ge** [comment]
The `px-rangepicker`, `px-datetime-range-field`, and `px-datetime-field`all require that there is room in the implementation for the validation to be displayed correctly. The background is transparent by default since we cannot predict what color background these components will be on. There is a css variable to set a background if absolutely necessary `--px-datetime-field-background-color`. 
We do understand that in some small cases the way validation is displayed will not work. Because of this I have exposed a `hideValidationMessages` property in order to hide the default display of the validation messages. Using this property is not recommend as it goes against the design of the component. I recommend before using this property that you revaluate your design and how this component is being displayed. Also if you use this property you will then have to implement your own way to display the validation message. 
The css variable was added in v1.0.4 of `px-datetime-field`
The `hideValidationMessages` property was add in v1.1.0 of `px-datetime-range-field` and v1.1.0 of `px-rangepicker`
