### ISSUE TITLE
Event sent with current date that overrides preset date

### ISSUE THREAD

**Issue by hannav95** [PredixDev/px-rangepicker#55]
## Expected behavior and actual behavior:
The rangepicker sends the a route-changed event when rendered with the current date, which overrides the date I set in the state for the rangepicker.

## Steps to reproduce the problem:
See code example below

## Environment:
Component version: 2.1.2
Browser: Chrome 63
OS: Windows 10

## Code example
[Code](https://glitch.com/edit/#!/px-rangepicker-error)
[Live Example](https://px-rangepicker-error.glitch.me/)

**Comment by randyaskin** [comment]
Your Glitch uses Polymer 2 and rangepicker v2.1.2, but hybrid compatibility wasn't added until v3.0.0 of px-rangepicker. That version also saw the removal of the `range` property due to the number of issues we had with all of our datetime components keeping the moment objects and strings in sync. `fromMoment` and `toMoment` are now the proper way to set the range in v3+ of px-rangepicker.

**Comment by hannav95** [comment]
My team updated to the v3.0.1, but when we built our product using Jenkins with Docker in Docker during the `bower install` we got an error: `ECONFLICT Unable to find suitable version for px-datetime-common`. So we reverted back to version 2.1.2

**Comment by randyaskin** [comment]
You were likely still using previous versions of some of the other datetime components (field, picker, range panel, or rangefield) which are all at `^2.0.0` now.

**Comment by hannav95** [comment]
The only datetime component we use is rangepicker. When I update the bower.json in the [glitch project](https://glitch.com/edit/#!/px-rangepicker-error?path=bower.json:6:29) to the latest version of rangepicker (v3.1.0), I get the same bower install error there too.

**Comment by benoitjchevalier** [comment]
Hello,

this is caused by your old bower_components folder not being cleaned before rerunning bower. I'm not sure how you would clean it on Jenkins (you would just need to clean it once for this upgrade) but you can do it on glitch and see that it fixes it: glitch project name -> advanced options -> open console -> rm -rf bower_components

**Comment by hannav95** [comment]
Okay, so updated to current rangepicker, but now now the ['fromMoment' in the rangepicker](https://px-rangepicker-error.glitch.me/) isn't rendering

**Comment by benoitjchevalier** [comment]
This is the new expected behavior as described in the [release notes](https://github.com/PredixDev/px-rangepicker/releases): 

- Polymer 1.x/2.x hybrid support
- range property no longer exists, use fromMoment and toMoment as the source of truth - fixes the problem of flickering / multiple event calls when any of the three properties were changed in the past
- Rangepicker will now have an empty state if fromMoment and toMoment are not specified or picked by the user (#32)
- Now uses iron-dropdown for more intelligent positioning of the range panel dropdown (#18)
- Updated min and max to minDate and maxDate to align with field
- Added fromMoment and toMoment arguments to validate function call
- Updated tests

**Comment by hannav95** [comment]
Right, but I do specify the fromMoment and toMoment in [lines 41 & 42](https://glitch.com/edit/#!/px-rangepicker-error?path=src/app.jsx:19:43)

**Comment by benoitjchevalier** [comment]
There are several problems with your glitch:
- moment object don't have `value` property to my knowledge, so the from and to moment were set to null. You want to pass those objects directly
- use Px.moment instead of moment, this will ensure that the right version of the moment object is created (in this instance the moment object created had no knowledge of timezones)
- because moment object can't be serialized you can't bind them directly in react. You have to assign them to the web component through a reference to the web component instead.

I've modified your glitch to make it functional:
https://glitch.com/edit/#!/profuse-vulture?path=src/app.jsx

**Comment by hannav95** [comment]
Great, thank you @benoitjchevalier!
