### ISSUE TITLE
Keyboard change not triggering events

### ISSUE THREAD

**Issue by jonniespratley** [PredixDev/px-rangepicker#56]
## Expected behavior and actual behavior:

Change hour/minute/second with keyboard and have `range-changed` or `px-datetime-range-submitted` fire event

## Steps to reproduce the problem:

Well I would show you a CodePen, but for some reason, your naming conventions are all jacked up and code pen demo is showing the following error for `pxmoment-timezone/builds/moment-timezone-with-data.min.js` I dont know why this repo does not have the `px-` like all others.

But attach event listener for the range changed and change value with keyboard the change event never fires.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

latest, Chrome Version 63.0.3239.84, Mac OSX, Hardware? really?

**Comment by randyaskin** [comment]
We are looking into the CodePen issue. But the component is functioning as expected - the `px-datetime-range-submitted` event is fired when you blur away from the component, hit the Enter key, or click the Apply button inside the panel. It is not fired every single time you increment/decrement an entry, because the user could hit the Escape key or Cancel button in the panel to revert to whatever was previously selected.
